dbt_postgres_example:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: world
      password: world123
      port: 5432
      dbname: world-db
      schema: analytics
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds