services:
  db:
    container_name: database
    image: ghusta/postgres-world-db
    restart: always
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 80:8080